# Generated by Django 4.0.4 on 2022-08-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuturegfList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.IntegerField(max_length=4)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(blank=True, max_length=500, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
