# Generated by Django 4.0.4 on 2022-08-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.IntegerField()),
            ],
        ),
    ]
