# Generated by Django 4.0.4 on 2022-08-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, height_field=100, null=True, upload_to='img/Customer/', width_field=100)),
            ],
        ),
    ]
