# Generated by Django 4.0.4 on 2022-08-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, height_field='100', null=True, upload_to='img/Customer/', width_field='100'),
        ),
    ]
